program test_simple;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.IOUtils,
  Tiger;

procedure TestPlatform(Plat : TTigerPlatform);
var
  LTiger: TTiger;
  LExitCode: Cardinal;
  LPlatform : string;
begin
  case Plat of
    tpWin64:   LPlatform := 'Windows on x64';
    tpLinux64: LPlatform := 'Linux on x64';
    tpMacOS64: LPlatform := 'MacOS on ARM64';
  end;

  WriteLn('Building '+LPlatform+' executable...');
  WriteLn('');

  LTiger := TTiger.Create(Plat);
  try
    LTiger.SetOptimizationLevel(0);  // Debug: enables heap leak reporting
    //LTiger.SetOptimizationLevel(2);
    LTiger.SetStatusCallback(
      procedure(const AText: string; const AUserData: Pointer)
      begin
        WriteLn(AText);
      end, nil);

    // macOS runtime automatically provides printf and exit from libSystem.B.dylib
    // No need to call ImportDll for basic functions

    LTiger.Func('main', vtVoid, True)
      .Call('printf', [LTiger.Str('Hello from Tiger codegen!'#10)])
      .Call('printf', [LTiger.Str('This binary was generated by Tiger!'#10)])
      .Call('Tiger_Halt', [LTiger.Int64(0)])
    .EndFunc();

    LTiger.TargetExe(TPath.Combine('output', 'test_'+LPlatform.Substring(0,3)), ssConsole);
    
    if LTiger.Build(False, @LExitCode) then
    begin
      WriteLn('');
      WriteLn('========================================');
      WriteLn('Build successful!');
      WriteLn('Output file: output\test_macos');
      WriteLn('');
      WriteLn('Next steps:');
      WriteLn('1. Copy output\test_macos to an Apple Silicon Mac');
      WriteLn('2. In Terminal: chmod +x test_macos');
      WriteLn('3. Run: ./test_macos');
      WriteLn('========================================');
    end
    else
    begin
      WriteLn('');
      WriteLn('Build failed!');
      if LTiger.HasErrors() then
        WriteLn(LTiger.GetErrorText());
    end;
  finally
    LTiger.Free();
  end;
end;

begin
  try
    for var plat := Low(TTigerPlatform) to High(TTigerPlatform) do
      TestPlatform(plat);
    ReadLn;
  except
    on E: Exception do
    begin
      WriteLn('Error: ', E.Message);
      ExitCode := 1;
    end;
  end;
end.
