program test_simple;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.IOUtils,
  Tiger;

function PlatformLabel(const Plat: TTigerPlatform): string;
begin
  case Plat of
    tpWin64:      Result := 'Windows on x64';
    tpLinux64:    Result := 'Linux on x64';
    tpMacOS64:    Result := 'MacOS on ARM64';
    tpLinuxARM64: Result := 'Linux on ARM64';
  else
    Result := 'Unknown platform';
  end;
end;

function OutputName(const Plat: TTigerPlatform): string;
begin
  case Plat of
    tpWin64:      Result := 'test_win';
    tpLinux64:    Result := 'test_lin';
    tpMacOS64:    Result := 'test_mac';
    tpLinuxARM64: Result := 'test_linarm';
  else
    Result := 'test_unknown';
  end;
end;

procedure TestPlatform(Plat : TTigerPlatform);
var
  LTiger: TTiger;
  LExitCode: Cardinal;
  LPlatform : string;
  LOutputName: string;
begin
  LPlatform := PlatformLabel(Plat);
  LOutputName := OutputName(Plat);

  WriteLn('Building '+LPlatform+' executable...');
  WriteLn('');

  LTiger := TTiger.Create(Plat);
  try
    LTiger.SetOptimizationLevel(0);  // Debug: enables heap leak reporting
    //LTiger.SetOptimizationLevel(2);
    LTiger.SetStatusCallback(
      procedure(const AText: string; const AUserData: Pointer)
      begin
        WriteLn(AText);
      end, nil);

    if Plat = tpWin64 then
      LTiger.ImportDll('msvcrt.dll', 'printf', [vtPointer], vtInt32, True)
    else if Plat <> tpMacOS64 then
      LTiger.ImportDll('libc.so.6', 'printf', [vtPointer], vtInt32, True);

    LTiger.Func('main', vtVoid, True)
      .Call('printf', [LTiger.Str('Hello from Tiger codegen!'#10)])
      .Call('printf', [LTiger.Str('This binary was generated by Tiger!'#10)])
      .Call('Tiger_Halt', [LTiger.Int64(0)])
    .EndFunc();

    LTiger.TargetExe(TPath.Combine('output', LOutputName), ssConsole);
    
    if LTiger.Build(False, @LExitCode) then
    begin
      WriteLn('');
      WriteLn('========================================');
      WriteLn('Build successful!');
      WriteLn('Output file: output\' + LOutputName);
      WriteLn('');
      WriteLn('Next steps:');
      if Plat = tpWin64 then
        WriteLn('1. Run: .\output\' + LOutputName + ' in a command line window')
      else if Plat = tpMacOS64 then
      begin
        WriteLn('1. chmod +x output/' + LOutputName);
        WriteLn('2. Run: ./output/' + LOutputName);
      end
      else if Plat = tpLinuxARM64 then
      begin
        WriteLn('1. Run under linux/arm64 (e.g. ./tests/run_linux_arm64.sh after copying to tests/bin/output/linarm)');
        WriteLn('2. Or on a Linux ARM64 host: chmod +x output/' + LOutputName + ' && ./output/' + LOutputName);
      end
      else
      begin
        WriteLn('1. On a Linux x64 host: chmod +x output/' + LOutputName);
        WriteLn('2. Run: ./output/' + LOutputName);
      end;
      WriteLn('========================================');
    end
    else
    begin
      WriteLn('');
      WriteLn('Build failed!');
      if LTiger.HasErrors() then
        WriteLn(LTiger.GetErrorText());
    end;
  finally
    LTiger.Free();
  end;
end;

begin
  try
    for var plat in [tpWin64, tpLinux64, tpMacOS64, tpLinuxARM64] do
      TestPlatform(plat);
    ReadLn;
  except
    on E: Exception do
    begin
      WriteLn('Error: ', E.Message);
      ExitCode := 1;
    end;
  end;
end.
